openapi: 3.0.3
info:
  title: Phythaph
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/auth/register:
    post:
      summary: 'Register new user'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"Registration Successful\",\n   \"data\": {\n      [UserData]\n   }"
        400:
          description: 'Registration Failed'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Registration Failed'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Registration Failed'
      tags:
        - 'Auth APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: aut
                last_name:
                  type: string
                  description: ''
                  example: soluta
                email:
                  type: string
                  description: ''
                  example: totam
                password:
                  type: string
                  description: ''
                  example: quae
              required:
                - first_name
                - last_name
                - email
                - password
      security: []
  /api/auth/login:
    post:
      summary: 'User Login'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"Login Successful\",\n   \"data\": {\n      \"user\": {\n          ...\n      },\n      \"token\": jwt_token\n   }"
        400:
          description: 'Invalid Credentials'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Invalid Credentials'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Invalid Credentials'
      tags:
        - 'Auth APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: optio
                password:
                  type: string
                  description: ''
                  example: voluptatum
              required:
                - email
                - password
      security: []
  '/api/auth/email/verify/{id}':
    get:
      summary: 'Email Verification'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  success: false
                  message: 'Invalid/Expired url provided.'
                properties:
                  status:
                    type: boolean
                    example: false
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Invalid/Expired url provided.'
      tags:
        - 'Auth APIs'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the verify.'
        example: similique
        required: true
        schema:
          type: string
  '/api/auth/email/resend/{id}':
    get:
      summary: 'Resend Verification Email'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"Email verification link sent on your email!\",\n   }"
        400:
          description: 'Email already verified!'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Email already verified!'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Email already verified!'
      tags:
        - 'Auth APIs'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the resend.'
        example: voluptatem
        required: true
        schema:
          type: string
tags:
  -
    name: 'Auth APIs'
    description: ''
