openapi: 3.0.3
info:
  title: Phythaph
  description: ''
  version: 1.0.0
servers:
  -
    url: 'https://phythaph-web-app-new.herokuapp.com'
paths:
  /api/auth/register:
    post:
      summary: 'Register new user'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"Registration Successful\",\n   \"data\": {\n      [UserData]\n   }"
        400:
          description: 'Registration Failed'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Registration Failed'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Registration Failed'
      tags:
        - 'Auth APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: ''
                  example: alias
                last_name:
                  type: string
                  description: ''
                  example: est
                email:
                  type: string
                  description: ''
                  example: dicta
                password:
                  type: string
                  description: ''
                  example: ipsa
              required:
                - first_name
                - last_name
                - email
                - password
      security: []
  /api/auth/login:
    post:
      summary: 'User Login'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"Login Successful\",\n   \"data\": {\n      \"user\": {\n          ...\n      },\n      \"token\": jwt_token\n   }"
        400:
          description: 'Invalid Credentials'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Invalid Credentials'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Invalid Credentials'
      tags:
        - 'Auth APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: voluptatem
                password:
                  type: string
                  description: ''
                  example: voluptas
              required:
                - email
                - password
      security: []
  '/api/auth/email/verify/{id}':
    get:
      summary: 'Email Verification'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: false
                  success: false
                  message: 'Invalid/Expired url provided.'
                properties:
                  status:
                    type: boolean
                    example: false
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Invalid/Expired url provided.'
      tags:
        - 'Auth APIs'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the verify.'
        example: voluptatibus
        required: true
        schema:
          type: string
  '/api/auth/email/resend/{id}':
    get:
      summary: 'Resend Verification Email'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"Email verification link sent on your email!\",\n   }"
        400:
          description: 'Email already verified!'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Email already verified!'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Email already verified!'
      tags:
        - 'Auth APIs'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the resend.'
        example: tempore
        required: true
        schema:
          type: string
  /api/auth/password/forgot-password:
    post:
      summary: 'Send Reset Password Link'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"Mail sent successfully\",\n   }"
        400:
          description: 'Error Message'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Error Message'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Error Message'
      tags:
        - 'Auth APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: aut
              required:
                - email
      security: []
  /api/auth/password/reset:
    post:
      summary: 'Reset Password'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"Password reset successfully\",\n   }"
        400:
          description: 'Error Message'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Error Message'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Error Message'
      tags:
        - 'Auth APIs'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: ''
                  example: nostrum
                token:
                  type: string
                  description: ''
                  example: cum
                password:
                  type: string
                  description: ''
                  example: sit
              required:
                - email
                - token
                - password
      security: []
  /api/setup:
    post:
      summary: 'Registration Setup'
      description: 'Complete user registration.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"Setup Complete!\",\n   \"data\": {\n      \"user\": {\n          ...\n      }\n   }"
      tags:
        - 'Auth APIs'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                account_type:
                  type: string
                  description: optional
                  example: accusantium
                phone:
                  type: string
                  description: optional
                  example: praesentium
                gender:
                  type: string
                  description: optional
                  example: maxime
                birthday:
                  type: date
                  description: optional
                  example: quia
                address:
                  type: string
                  description: optional
                  example: quaerat
                house_number:
                  type: string
                  description: optional
                  example: sunt
                street:
                  type: string
                  description: optional
                  example: eum
                lga:
                  type: string
                  description: optional
                  example: odit
                lcda:
                  type: string
                  description: optional
                  example: nostrum
                company_name:
                  type: string
                  description: optional
                  example: illum
                company_phone:
                  type: string
                  description: optional
                  example: laudantium
                country:
                  type: string
                  description: optional
                  example: veniam
                postal_code:
                  type: string
                  description: optional
                  example: vel
                city:
                  type: string
                  description: optional
                  example: ipsa
                state:
                  type: string
                  description: optional
                  example: in
      security: []
  /api/auth/logout:
    get:
      summary: 'User Logout'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Logout Successful'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Logout Successful'
      tags:
        - 'Auth APIs'
      security: []
  /api/user:
    get:
      summary: 'User Data'
      description: 'Get user data'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"\",\n   \"data\": {\n      \"user\": {\n          ...\n      }\n   }"
        404:
          description: 'User not found'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'User not found'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'User not found'
      tags:
        - 'Auth APIs'
      security: []
  /api/me:
    get:
      summary: 'User Data'
      description: 'Get user data.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: "{\n   \"success\": true,\n   \"message\": \"\",\n   \"data\": {\n      \"user\": {\n          ...\n      }\n   }"
        404:
          description: 'User not found'
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'User not found'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'User not found'
      tags:
        - 'Auth APIs'
      security: []
tags:
  -
    name: 'Auth APIs'
    description: ''
